### ISSUE TITLE
Compatibility issues with fluentd plugins

### ISSUE THREAD

**Issue by PranavBhatSF** [kube-logging/fluentd-images#147]
## Usecase
We need to push kubernetes pod logs to Azure, S3 or Splunk based on the configuration.

## What we have done
Built a custom image with Fluentd image as base and included the required plugins.
Dockerfile

```
FROM ghcr.io/kube-logging/fluentd:v1.16-4.9-full as base-fluentd

# add azure storage append blob plugin
RUN gem install fluent-plugin-azure-storage-append-blob -v 0.2.1
# add aws s3 plugin
RUN gem install fluent-plugin-s3 -v 1.7.2
# add splunk plugin
RUN gem install fluent-plugin-splunk-hec -v 1.3.2
```

## Issue
Fluentd is pushing logs to S3 and Azure. But when we configure splunk as destination, `fluentd-configcheck` pod fails with the below error
```
....
/usr/lib/ruby/3.1.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate swd-2.0.2, because faraday-1.10.3 conflicts with faraday (~> 2.0) (Gem::ConflictError)
....
/usr/lib/ruby/3.1.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate swd-2.0.2, because faraday-1.10.3 conflicts with faraday (~> 2.0) (Gem::ConflictError)
```

**Comment by pepov** [comment]
What happens if you try `ghcr.io/kube-logging/fluentd:v1.16-4.9-filters` instead of full?

**Comment by danialram** [comment]
Even with ghcr.io/kube-logging/fluentd:v1.16-4.9-filters we are seeing same issue.

**Comment by pepov** [comment]
We had this issue with the azure plugin and had to remove it because of the same reason. I'm not aware of a good resolution to this problem and would be good if someone could take a deeper look. To make things worse the underlying plugin is not maintained and the [ruby library is already deprecated](https://azure.microsoft.com/en-gb/updates/retirement-notice-the-azure-storage-ruby-client-libraries-will-be-retired-on-13-september-2024/). We would need to look at a more future proof solution here that is based on the supported Rest API ideally.
