### ISSUE TITLE
v1.15-ruby3-build.87 - unkown keyword: :logger

### ISSUE THREAD

**Issue by genofire** [kube-logging/fluentd-images#46]
image-tag: v1.15-ruby3-build.87
```
│ fluentd 2023-06-06 10:13:51 +0000 [error]: fluent/log.rb:372:error: unexpected error error_class=ArgumentError error="unknown keyword: :logger"                                                                                             │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/async-2.5.1/lib/async/scheduler.rb:26:in `initialize'                                                                    │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/async-2.5.1/lib/async/reactor.rb:19:in `initialize'                                                                      │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/http_server/server.rb:41:in `new'                                                │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/http_server/server.rb:41:in `initialize'                                         │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/http_server.rb:69:in `new'                                                       │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/http_server.rb:69:in `http_server_create_http_server'                            │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-prometheus-2.0.3/lib/fluent/plugin/in_prometheus.rb:109:in `start'                                         │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:203:in `block in start'                                                          │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'                                           │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:191:in `each'                                                                    │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:191:in `block in lifecycle'                                                      │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:178:in `each'                                                                    │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:178:in `lifecycle'                                                               │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:202:in `start'                                                                   │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/engine.rb:248:in `start'                                                                       │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/engine.rb:147:in `run'                                                                         │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:783:in `block in run_worker'                                                     │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:1056:in `main_process'                                                           │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:774:in `run_worker'                                                              │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:370:in `<top (required)>'                                                   │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'                                                                     │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'                                                                     │
│ fluentd   2023-06-06 10:13:51 +0000 [error]: fluent/supervisor.rb:1055:main_process: /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'    
```

**Comment by genofire** [comment]
Works, thanks.
